IssueTracker/Models/Notification.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using IssueTracker.Models.Enums;


namespace IssueTracker.Models;

public class Notification
{
    // This operates as the primary key for identity framework
    public int Id { get; set; }
    
    [Required]
    [StringLength(50,ErrorMessage = "The {0} must be at least {2} and a max {1} characters."),MinLength(2)]
    [DisplayName("Notification Title")]
    public string Title { get; set; }
    
    [Required]
    [DisplayName("Ticket Message")]
    public string Message { get; set; }
    
    public int NotificationTypeId { get; set; }
    public NotificationType NotificationType => (NotificationType)NotificationTypeId;
    
    [DisplayName("Date")]
    [DataType(DataType.Date)]
    public DateTimeOffset Created { get; set; }
    
    public string TimeSinceCreated
    {
        get
        {
            TimeSpan timeSince = DateTime.Now - Created;

            if (timeSince.Days > 30)
                return "Over a month ago";

            if (timeSince.Days > 1)
                return $"{timeSince.Days} days ago";

            if (timeSince.Days == 1)
                return $"Yesterday";

            if (timeSince.Hours > 1)
                return $"{timeSince.Hours} hours ago";

            if (timeSince.Minutes > 1)
                return $"{timeSince.Minutes} minutes ago";

            return "Just now";
        }
    }

    [DisplayName("Has been viewed")] public bool Viewed { get; set; }
    
    // This is a foreign key in the database.  This corresponds to another table on the database.
    [DisplayName("Ticket")]
    public int? TicketId { get; set; }
    
    // This is a foreign key in the database.  This corresponds to another table on the database.
    [Required]
    [DisplayName("Project")]
    public int? ProjectId { get; set; }
    
    // This is a foreign key in the database.  This corresponds to another table on the database.
    [Required]
    [DisplayName("Recipent")]
    public string RecipentId { get; set; }
    
    // This is a foreign key in the database.  This corresponds to another table on the database.
    [Required]
    [DisplayName("Sender")]
    public string? SenderId { get; set; }
    
    // This is a foreign key in the database.  This corresponds to another table on the database.
    [Required]
    [DisplayName("Company")]
    public int CompanyId { get; set; }
    
    // Virtuals
    // When entity framework sees virtuals it allows easy loading and change tracking. This is opposed to eager loading. Essentially we get the foreign keys above and then the virtual objects below
    // Navigations properties. These allows us to specify the relationships of one class to another. IE we need to specify these to create the relations between the tables in the database.
    // These are not stored in the database
    
    public virtual Ticket? Ticket { get; set; }
    
    public virtual ITUser? Sender { get; set; }
    
    public virtual ITUser? Recipent { get; set; }
    
    public virtual Project? Project { get; set; }
    
    public virtual Company Company { get; set; }
    

}

IssueTracker/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IssueTracker.Data;
using IssueTracker.Models;
using IssueTracker.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace IssueTracker.Controllers
{
    public class NotificationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ITUser> _userManager;
        private readonly INotificationService _notificationService;

        public NotificationController(
            ApplicationDbContext context,
            UserManager<ITUser> userManager,
            INotificationService notificationService
            )
        {
            _context = context;
            _userManager = userManager;
            _notificationService = notificationService;
        }

        // GET: Notification
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Notifications.Include(n => n.Recipent).Include(n => n.Sender).Include(n => n.Ticket);
            return View(await applicationDbContext.ToListAsync());
        }
        
        [HttpGet]
        [Authorize]
        public async Task<ViewResult> MyNotifications()
        {
            ITUser? appUser = await _userManager.GetUserAsync(User);

            List<Notification> notifications = appUser is not null ? await _notificationService.GetAllNotificationsForUserAsync(appUser) : new List<Notification>();

            return View(notifications);
        }
        
        [HttpGet]
        [Authorize]
        public async Task<RedirectToActionResult> MarkAsRead(int id)
        {
            Notification? notification = await _notificationService.GetByIdAsync(id);

            if (notification is not null)
            {
                if (notification.RecipentId == (await _userManager.GetUserAsync(User)).Id)
                    await _notificationService.MarkAsRead(notification);
                else
                    return RedirectToAction(nameof(NotAuthorized));
            }

            return RedirectToAction(nameof(MyNotifications));
        }

        [HttpGet]
        public ViewResult NotAuthorized()
        {
            return View();
        }

        // GET: Notification/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Notifications == null)
            {
                return NotFound();
            }

            var notification = await _context.Notifications
                .Include(n => n.Recipent)
                .Include(n => n.Sender)
                .Include(n => n.Ticket)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notification == null)
            {
                return NotFound();
            }

            return View(notification);
        }

        // GET: Notification/Create
        public IActionResult Create()
        {
            ViewData["RecipentId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["SenderId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TicketId"] = new SelectList(_context.Tickets, "Id", "Description");
            return View();
        }

        // POST: Notification/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Message,Created,Viewed,TicketId,RecipentId,SenderId")] Notification notification)
        {
            if (ModelState.IsValid)
            {
                _context.Add(notification);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RecipentId"] = new SelectList(_context.Users, "Id", "Id", notification.RecipentId);
            ViewData["SenderId"] = new SelectList(_context.Users, "Id", "Id", notification.SenderId);
            ViewData["TicketId"] = new SelectList(_context.Tickets, "Id", "Description", notification.TicketId);
            return View(notification);
        }

        // GET: Notification/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Notifications == null)
            {
                return NotFound();
            }

            var notification = await _context.Notifications.FindAsync(id);
            if (notification == null)
            {
                return NotFound();
            }
            ViewData["RecipentId"] = new SelectList(_context.Users, "Id", "Id", notification.RecipentId);
            ViewData["SenderId"] = new SelectList(_context.Users, "Id", "Id", notification.SenderId);
            ViewData["TicketId"] = new SelectList(_context.Tickets, "Id", "Description", notification.TicketId);
            return View(notification);
        }

        // POST: Notification/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Message,Created,Viewed,TicketId,RecipentId,SenderId")] Notification notification)
        {
            if (id != notification.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(notification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotificationExists(notification.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RecipentId"] = new SelectList(_context.Users, "Id", "Id", notification.RecipentId);
            ViewData["SenderId"] = new SelectList(_context.Users, "Id", "Id", notification.SenderId);
            ViewData["TicketId"] = new SelectList(_context.Tickets, "Id", "Description", notification.TicketId);
            return View(notification);
        }

        // GET: Notification/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Notifications == null)
            {
                return NotFound();
            }

            var notification = await _context.Notifications
                .Include(n => n.Recipent)
                .Include(n => n.Sender)
                .Include(n => n.Ticket)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notification == null)
            {
                return NotFound();
            }

            return View(notification);
        }

        // POST: Notification/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Notifications == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Notifications'  is null.");
            }
            var notification = await _context.Notifications.FindAsync(id);
            if (notification != null)
            {
                _context.Notifications.Remove(notification);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotificationExists(int id)
        {
          return (_context.Notifications?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

IssueTracker/Views/Notification/Create.cshtml
@model IssueTracker.Models.Notification

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Notification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Viewed" /> @Html.DisplayNameFor(model => model.Viewed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="TicketId" class="control-label"></label>
                <select asp-for="TicketId" class ="form-control" asp-items="ViewBag.TicketId"></select>
            </div>
            <div class="form-group">
                <label asp-for="RecipentId" class="control-label"></label>
                <select asp-for="RecipentId" class ="form-control" asp-items="ViewBag.RecipentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SenderId" class="control-label"></label>
                <select asp-for="SenderId" class ="form-control" asp-items="ViewBag.SenderId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IssueTracker/Views/Notification/Delete.cshtml
@model IssueTracker.Models.Notification

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Notification</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Viewed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Viewed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sender.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recipent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recipent.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IssueTracker/Views/Notification/Details.cshtml
@model IssueTracker.Models.Notification

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Notification</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Viewed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Viewed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sender.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recipent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recipent.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IssueTracker/Views/Notification/Edit.cshtml
@model IssueTracker.Models.Notification

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Notification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Viewed" /> @Html.DisplayNameFor(model => model.Viewed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="TicketId" class="control-label"></label>
                <select asp-for="TicketId" class="form-control" asp-items="ViewBag.TicketId"></select>
                <span asp-validation-for="TicketId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipentId" class="control-label"></label>
                <select asp-for="RecipentId" class="form-control" asp-items="ViewBag.RecipentId"></select>
                <span asp-validation-for="RecipentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SenderId" class="control-label"></label>
                <select asp-for="SenderId" class="form-control" asp-items="ViewBag.SenderId"></select>
                <span asp-validation-for="SenderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IssueTracker/Views/Notification/Index.cshtml
@model IEnumerable<IssueTracker.Models.Notification>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Viewed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ticket)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recipent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Viewed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ticket.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sender.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recipent.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

IssueTracker/Views/Notification/MyNotifications.cshtml
@using System.Web;
@using IssueTracker.Models.Enums
@model IEnumerable<Notification>

@{
    IEnumerable<Notification> newNotifications = Model.Where(n => !n.Viewed);
    IEnumerable<Notification> oldNotifications = Model.Where(n => n.Viewed);
}

<div class="pagetitle">
    <h1>Notifications</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Account</li>
            <li class="breadcrumb-item active">Notifications</li>
        </ol>
    </nav>
</div>

<section class="section">
    <div class="row align-items-top">

        <h4>New Notifications</h4>
        @if(newNotifications.Count() == 0)
        {
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">No new notifications</h5>
                        <p class="card-text">Nothing here! You're all up to date.</p>
                    </div>
                </div>
            </div>
        }
        else
        {
            foreach(Notification notification in newNotifications)
            {
                <div class="col-lg-6">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">@notification.Title</h5>
                            <h6 class="card-subtitle mb-2 text-muted">@notification.Created.ToString()</h6>
                            <partial name="NotificationBodyPartial" model="notification" />
                        </div>
                        <div class="card-footer">
                        @switch((NotificationType)notification.NotificationTypeId)
                        {
                            case (NotificationType.CompanyInvite):
                                <!-- Accept -->
                                <a class="btn btn-success" 
                                asp-controller="Company" asp-action="AcceptCompanyInvite"
                                asp-route-notificationId="@notification.Id">Accept</a>

                                <!-- Decline -->
                                <a class="btn btn-danger"
                                asp-controller="Company" asp-action="RejectCompanyInvite"
                                asp-route-notificationId="@notification.Id">Decline</a>
                                break;

                            default:
                                <a class="btn btn-secondary" asp-controller="Notification" asp-action="MarkAsRead" asp-route-id="@notification.Id">Ok</a>
                                break;
                        }
                        </div>
                    </div>

                </div>
            }
        }

        <h4>Old News</h4>
        @if (oldNotifications.Count() == 0)
        {
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Empty</h5>
                        <p class="card-text">No history to show.</p>
                    </div>
                </div>
            </div>
        }
        else
        {
            foreach (Notification notification in oldNotifications)
            {
                <div class="col-lg-6">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">@notification.Title</h5>
                            <h6 class="card-subtitle mb-2 text-muted">@notification.Created.ToString()</h6>
                            <partial name="NotificationBodyPartial" model="notification" />
                        </div>
                    </div>

                </div>
            }
        }

    </div>
</section>

IssueTracker/Views/Notification/NotificationBodyPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using IssueTracker.Models.Enums
@model Notification

@inject UserManager<ITUser> UserManager

@{
    ITUser sendingUser = await UserManager.FindByIdAsync(Model.SenderId);
}


@switch (Model.NotificationType)
{
    case (NotificationType.CompanyInvite):
        <p class="card-text">
            @sendingUser.FullName has invited you to join their company.
        </p>
        break;


    case (NotificationType.CompanyInviteAccepted):
        <p class="card-text">
            <a asp-controller="Company" asp-action="ViewMember" asp-route-userId="@sendingUser.Id">@sendingUser.FullName</a> has accepted the invite to join your company. 
            You can now assign them a role and job title. Visit the <a asp-controller="Company" asp-action="ManageMembers">Manage Team Members</a> page to do so.
        </p>
        break;

    case (NotificationType.CompanyInviteRejected):
        <p class="card-text">
            @sendingUser.FullName declined the invite to join your company.
        </p>
        break;

    case (NotificationType.NewProject):
        <p class="card-text">
            You have been added to the team for the following project: <a asp-controller="Project" asp-action="Details" asp-route-projectId="@Model.Project!.Id">@Model.Project!.Name</a>
        </p>
        break;

    case (NotificationType.NewTicket):
        <p class="card-text">
            You have a new ticket to accept on the <a asp-controller="Project" asp-action="Details" asp-route-projectId="@Model.Project!.Id">@Model.Project!.Name</a> project. 
            Ticket Title: <a asp-controller="Ticket" asp-action="Details" asp-route-ticketId="@Model.Ticket!.Id">@Model.Ticket!.Title</a>
        </p>
        break;

    case (NotificationType.Mention):
        <p class="card-text">
            @sendingUser.FullName left you a comment in the <a asp-controller="Ticket" asp-action="Details" asp-route-ticketId="@Model.TicketId">@Model.Ticket!.Title</a> ticket. 
            Be sure to read it!"</p>
        break;

    case (NotificationType.RemovedFromCompany):
        <p class="card-text">
            Hopefully we're not the ones breaking the news to you, but you were removed from your company. On the bright side, you can now be invited to a different one, or create your own.
        </p>
        break;

    default:
        break;
}